language: node_js
sudo: false
notifications:
  email: false
node_js:
  - stable
script:
  - npm test
before_install:
  # Decrypt deployment key
  - openssl aes-256-cbc -K $encrypted_d95c70ccd684_key -iv $encrypted_d95c70ccd684_iv
    -in .travis/deploy_resin_ed25519.enc -out .travis/deploy_resin_ed25519 -d
  # Start ssh-agent
  - eval "$(ssh-agent -s)"
  # Add deploy key
  - chmod 600 .travis/deploy_resin_ed25519
  - ssh-add .travis/deploy_resin_ed25519
deploy:
  provider: script
  script: scripts/deploy-travis.sh
  on:
    branch: master
