language: node_js
sudo: false
notifications:
  email: false
node_js:
  - stable
script:
  - npm test
before_install:
  # Start ssh-agent
  - eval "$(ssh-agent -s)"
  # Decrypt deployment key
  - openssl aes-256-cbc -K $encrypted_d95c70ccd684_key -iv $encrypted_d95c70ccd684_iv
    -in .travis/id_ed25519.enc -out .travis/id_ed25519 -d
  # Add deploy key
  - cp .travis/id_ed25519 ~/.ssh/id_ed25519
  - chmod 0600 ~/.ssh/id_ed25519
  - ssh-add ~/.ssh/id_ed25519
  - cat .travis/known_hosts >> ~/.ssh/known_hosts
deploy:
  provider: script
  script: scripts/deploy-travis.sh
  on:
    branch: master
